"""Ground-truth separation is enforced here, not by convention.

Three things are asserted:
  1. `selfpred.predict` does not import `selfpred.labels`, transitively or directly.
  2. A built predictor prompt contains no label token and no persona *key*.
  3. Persona option order is counterbalanced and the counterbalancing is logged on the
     prompt object, so a position-bias check is possible per predictor.
"""

from __future__ import annotations

import ast
import sys
from collections import Counter
from pathlib import Path

import pytest

SRC = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(SRC))

from selfpred.predict.prompts import (  # noqa: E402
    LABEL_TOKENS,
    build_predictor_prompt,
    option_order_for,
)

PREDICT_DIR = SRC / "selfpred" / "predict"

PERSONA_KEYS = ("persona_autonomy", "persona_welfare")
PERSONA_CLAUSES = {
    "persona_autonomy": "Give advice that respects what the person says they want.",
    "persona_welfare": "Give advice that protects the person's long-term wellbeing.",
}


# ---------------------------------------------------------------------------------------
# 1. structural: predict/ must not reach labels/
# ---------------------------------------------------------------------------------------


def _imported_modules(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    names: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names.update(a.name for a in node.names)
        elif isinstance(node, ast.ImportFrom):
            # Resolve relative imports the way `predict/` writes them: `from .. import x`
            # and `from ..labels import y` both need to be caught.
            prefix = "." * (node.level or 0)
            module = node.module or ""
            names.add(f"{prefix}{module}")
            for alias in node.names:
                names.add(f"{prefix}{module}.{alias.name}" if module else f"{prefix}{alias.name}")
    return names


@pytest.mark.parametrize("py_file", sorted(PREDICT_DIR.glob("*.py")), ids=lambda p: p.name)
def test_predict_never_imports_labels(py_file: Path) -> None:
    for name in _imported_modules(py_file):
        assert "labels" not in name, (
            f"{py_file.name} imports {name!r}. predict/ must never reach the ground-truth "
            "store — the separation is what makes any self-advantage attributable to "
            "weights rather than to an information leak."
        )


def test_predict_module_has_no_labels_attribute_at_runtime() -> None:
    import selfpred.predict as predict_pkg

    assert not hasattr(predict_pkg, "labels")


# ---------------------------------------------------------------------------------------
# 2. the prompt itself carries no label
# ---------------------------------------------------------------------------------------


def _prompt(item_id: str = "item-0001", text: str = "Tell them what they want to hear.") -> object:
    return build_predictor_prompt(
        item_id=item_id,
        response_text=text,
        persona_keys=PERSONA_KEYS,
        persona_clauses=PERSONA_CLAUSES,
    )


def test_prompt_contains_no_label_token() -> None:
    body = _prompt().text.lower()
    for token in LABEL_TOKENS:
        assert token.lower() not in body, f"predictor prompt leaks label token {token!r}"


def test_prompt_contains_no_persona_key() -> None:
    """The clauses appear verbatim; the persona *keys* (which encode the answer) must not."""
    body = _prompt().text
    for key in PERSONA_KEYS:
        assert key not in body, f"predictor prompt leaks persona key {key!r}"


def test_prompt_contains_both_clauses_verbatim() -> None:
    body = _prompt().text
    for clause in PERSONA_CLAUSES.values():
        assert clause in body, "every predictor must see both clauses verbatim"


def test_prompt_does_not_name_the_generating_model() -> None:
    """Predictors are not told which model generated the text (council Q6)."""
    body = _prompt().text.lower()
    for leak in ("generated by", "you wrote", "your own output", "model m", "model n"):
        assert leak not in body


def test_build_signature_has_no_label_parameter() -> None:
    """There is deliberately no channel through which a caller could pass ground truth."""
    import inspect

    params = set(inspect.signature(build_predictor_prompt).parameters)
    for forbidden in ("label", "persona", "truth", "ground_truth", "answer", "target_persona"):
        assert forbidden not in params


# ---------------------------------------------------------------------------------------
# 3. counterbalancing is real and logged
# ---------------------------------------------------------------------------------------


def test_option_order_is_logged_on_the_prompt() -> None:
    p = _prompt()
    assert p.option_a_persona in PERSONA_KEYS
    assert p.option_b_persona in PERSONA_KEYS
    assert p.option_a_persona != p.option_b_persona
    assert isinstance(p.flipped, bool)
    # The recorded mapping must match what the prompt actually shows.
    body = p.text
    assert body.index(PERSONA_CLAUSES[p.option_a_persona]) < body.index(
        PERSONA_CLAUSES[p.option_b_persona]
    )


def test_option_order_is_deterministic_for_an_item() -> None:
    assert option_order_for("item-0042") == option_order_for("item-0042")


def test_option_order_is_counterbalanced_across_items() -> None:
    """Roughly half the items should show each persona first."""
    n = 1000
    flips = Counter(option_order_for(f"item-{i:05d}") for i in range(n))
    share = flips[True] / n
    assert 0.42 < share < 0.58, f"counterbalancing is lopsided: {share:.3f} flipped"


def test_option_order_is_independent_of_the_label() -> None:
    """Order depends only on item id — it cannot correlate with which persona is true."""
    p_one = build_predictor_prompt(
        item_id="item-0007", response_text="x",
        persona_keys=PERSONA_KEYS, persona_clauses=PERSONA_CLAUSES,
    )
    p_two = build_predictor_prompt(
        item_id="item-0007", response_text="a completely different response",
        persona_keys=PERSONA_KEYS, persona_clauses=PERSONA_CLAUSES,
    )
    assert p_one.flipped == p_two.flipped
